# Generated by Django 2.0.8 on 2019-09-18 03:37

from django.db import migrations, models
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalkContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', mdeditor.fields.MDTextField(verbose_name='说说正文')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.TextField(choices=[('y', '公开'), ('n', '私密')], default='y', verbose_name='发表状态')),
            ],
            options={
                'verbose_name': '说说内容',
                'verbose_name_plural': '说说内容',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='TalkTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='说说标签')),
            ],
            options={
                'verbose_name': '说说标签',
                'verbose_name_plural': '说说标签',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='talkcontent',
            name='tag',
            field=models.ManyToManyField(to='myzone.TalkTags', verbose_name='说说标签'),
        ),
    ]
