# Generated by Django 2.0.8 on 2019-09-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pk'], 'verbose_name': '添加图书', 'verbose_name_plural': '添加图书'},
        ),
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'verbose_name': '书单分类', 'verbose_name_plural': '书单分类'},
        ),
        migrations.AlterModelOptions(
            name='booktag',
            options={'verbose_name': '书单标签', 'verbose_name_plural': '书单标签'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-pk'], 'verbose_name': '添加电影', 'verbose_name_plural': '添加电影'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '添加文章', 'verbose_name_plural': '添加文章'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '文章标签', 'verbose_name_plural': '文章标签'},
        ),
    ]
