# Generated by Django 2.0.8 on 2019-04-29 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics', models.TextField(blank=True, null=True, verbose_name='网站统计代码')),
            ],
            options={
                'verbose_name': '自定义代码',
                'verbose_name_plural': '自定义代码',
            },
        ),
        migrations.CreateModel(
            name='FriendLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='网站名称')),
                ('link', models.URLField(verbose_name='网站地址')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='网站名称')),
                ('description', models.CharField(max_length=300, verbose_name='网站描述')),
                ('keywords', models.CharField(max_length=200, verbose_name='关键字')),
            ],
            options={
                'verbose_name': 'SEO设置',
                'verbose_name_plural': 'SEO设置',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='建站时间')),
                ('record_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='备案信息')),
            ],
            options={
                'verbose_name': '站点信息',
                'verbose_name_plural': '站点信息',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(blank=True, null=True, verbose_name='Github地址')),
                ('wei_bo', models.URLField(blank=True, null=True, verbose_name='微博地址')),
                ('zhi_hu', models.URLField(blank=True, null=True, verbose_name='知乎地址')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ号码')),
                ('wechat', models.CharField(blank=True, max_length=50, null=True, verbose_name='微信')),
            ],
            options={
                'verbose_name': '社交账号',
                'verbose_name_plural': '社交账号',
            },
        ),
    ]
