# Generated by Django 2.0.8 on 2019-04-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='网站副名称'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='网站主名称'),
        ),
    ]
