# Generated by Django 2.0.8 on 2019-04-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20190429_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='Official_WeChat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='微信公众号'),
        ),
    ]
