# Generated by Django 2.0.8 on 2019-04-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_social_official_wechat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='Official_WeChat',
            new_name='official_wechat',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='arrange_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='部署信息'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='development_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='开发信息'),
        ),
    ]
